### ISSUE TITLE
Unification of naming convention of groupId

### ISSUE THREAD

**Issue by btyanagawamg** [terasolunaorg/tutorial-apps#150]
## Description
The current groupId is as follows

| project | groupId |
| :------- | :-------- |
| todo | todo |
| todo-rest | todo |
| session-tutorial-init | com.example.session |
| session-tutorial-complete | com.example.session |
| first-spring-security | com.example.security |
| secure-login-demo | org.terasoluna.securelogin |

Unify the naming convention as follows

| project | groupId |
| :------- | :-------- |
| todo | com.example.todo |
| todo-rest | com.example.todo |
| session-tutorial-init | com.example.session |
| session-tutorial-complete | com.example.session |
| first-spring-security | com.example.security |
| secure-login-demo | com.example.securelogin |

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.5.x(master)
- [x] 5.4.x
- [x] 5.3.x
- [x] 5.2.x
- [x] 5.1.x
- [x] 5.0.x
- [x] 1.0.x
- [x] 1.6.x (m-j)
- [x] 1.6.x (m-t)

## Final Solution
(To be written later by project member)

## Issue Links
* terasolunaorg/guideline#3219

**Comment by yoshikawaa** [comment]
I am skeptical as to whether to change `todo` to `com.example.todo`.
This is because it is contrary to the original thought that deepening the package hierarchy is a matter of course although trying to implement the application easily.

However, we can understand the requirement that it is more manageable in the management of the project, so we will follow this policy.

**Comment by yoshikawaa** [comment]
@btyanagawamg 
Please link to the Issue of the guideline.
The tutorial should basically be modified as the guidelines change.
