### ISSUE TITLE
Column mapping fails in tutorial using JPA's blank project

### ISSUE THREAD

**Issue by btnoguchimnm** [terasolunaorg/tutorial-apps#40]
## Description
Column mapping fails in tutorial using TERASOLUNA FW version 5.3.0 JPA blank project (both single project and multiproject ).
Because the naming convention for automatically mapping DB column names and entities has been changed.

5.2.0.RELEASE In the past, the entity name of the camel case and the DB column name of the snake case were automatically mapped, but after 5.3.0 it is necessary to make the DB column name also a camel case if the entity is a camel case .

Use `@Column` annotation to explicitly specify column names for mapping
Alternatively,
It is necessary to change the DB column name to the camel case so that it can be automatically mapped.

## Possible Solutions
Please see Discription.

## Affects Version/s
* 5.3.0.RELEASE

## Fix Version/s
- [x] master(5.3.0.RELEASE)

## Issue Links
* https://github.com/terasolunaorg/guideline/issues/2476
* https://github.com/terasolunaorg/guideline/issues/2477

**Comment by kazuki43zoo** [comment]
This issue can also resolve by creating a class that implements the `PhysicalNamingStrategy` interface.
For more information, please see https://docs.jboss.org/hibernate/orm/5.0/userguide/html_single/Hibernate_User_Guide.html#naming.

Actually, the Spring Boot provide [a implementation class](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/orm/jpa/hibernate/SpringPhysicalNamingStrategy.java) of the `PhysicalNamingStrategy` since 1.4.

**I think we should consider to update development guideline.**

**Comment by btyoshikawaa** [comment]
@btnoguchimnm 
Please close after writing new issue for improvement.

**Comment by btnoguchimnm** [comment]
@btyoshikawaa 
I described the issue on improvement and made a link so close this issue.
https://github.com/terasolunaorg/guideline/issues/2477
